version: '2'

# git clone https://github.com/Loos/bike-database.git 
#
# The environment is setup to use jwilder/nginx-proxy and
# JrCs/docker-letsencrypt-nginx-proxy-companion but can easily be
# modified to be served by an alternative http server.

services:
  bike-database: 
    container_name: bike-database
    build: . 
    network_mode: "bridge"
    restart: always
    volumes:
      - data:/app/db
    expose:
      - "3000"
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    environment:
      - PORT=3000
      - VIRTUAL_HOST=bike-database.bikelover.org
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=bike-database.bikelover.org
      - LETSENCRYPT_EMAIL="bike@bikelover.org"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:

